# Generated by Django 5.2.6 on 2025-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_auth',
            field=models.BooleanField(default=True, help_text='Hiện nút Đăng nhập'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_home',
            field=models.BooleanField(default=True, help_text='Hiện nút Trang chủ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_intro',
            field=models.BooleanField(default=True, help_text='Hiện nút Giới thiệu'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_products',
            field=models.BooleanField(default=True, help_text='Hiện nút Sản phẩm'),
        ),
    ]
